// <auto-generated />
using System;
using Helm_Budget_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helm_Budget_System.Migrations.Helm_Budget_Db
{
    [DbContext(typeof(Helm_Budget_DbContext))]
    partial class Helm_Budget_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Helm_Budget_System.Models.BudgetSector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BudgetSectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("BudgetSector");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDescription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DescriptorDescriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DescriptorDescription");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDesignation", b =>
                {
                    b.Property<int>("DescriptorDesignationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescriptorDesignationID"), 1L, 1);

                    b.Property<int>("DescriptorDescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("TransactionDescriptorID")
                        .HasColumnType("int");

                    b.HasKey("DescriptorDesignationID");

                    b.HasIndex("DescriptorDescriptionID");

                    b.HasIndex("TransactionDescriptorID");

                    b.ToTable("DescriptorDesignation");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ExpenseCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("ExpenseCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.PayrollCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal?>("AnnualBenefitRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("FringeBenefitRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PayrollCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("PayrollCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.Revenue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BudgetSectorID")
                        .HasColumnType("int");

                    b.Property<int>("DescriptorDescriptionID")
                        .HasColumnType("int");

                    b.Property<decimal?>("OtherRevenue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("RevenueCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("RevenueComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevenueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevenueQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("RevenueRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BudgetSectorID");

                    b.HasIndex("DescriptorDescriptionID");

                    b.HasIndex("RevenueCategoryID");

                    b.HasIndex("SchoolID");

                    b.HasIndex("YearID");

                    b.ToTable("Revenue");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.RevenueCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("RevenueCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("RevenueCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("PriceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<string>("TicketName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TicketType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TransactionDescriptor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionDescriptorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("TransactionDescriptor");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelAirfare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("AgentFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("AgentFeeTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("BaggageCostTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("BaggagePerPerson")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("CostPerPerson")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCharter")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalAirfareExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TravelPartyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TravelPartyID");

                    b.ToTable("TravelAirfare");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelAuto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AutoOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TravelPartyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TravelPartyID");

                    b.ToTable("TravelAuto");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TravelCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BudgetSectorID")
                        .HasColumnType("int");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InState")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConference")
                        .HasColumnType("bit");

                    b.Property<int>("TravelCategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TravelStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TravelEntry");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelLodging", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("RoomRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TravelPartyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TravelPartyID");

                    b.ToTable("TravelLodging");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelMiscellaneousExpense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TravelEntryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TravelEntryID");

                    b.ToTable("TravelMiscellaneousExpense");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelParty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TravelEntryID")
                        .HasColumnType("int");

                    b.Property<string>("TravelerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("TravelEntryID");

                    b.ToTable("TravelParty");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelPerDiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BreakfastDays")
                        .HasColumnType("int");

                    b.Property<int>("DinnerDays")
                        .HasColumnType("int");

                    b.Property<int>("LunchDays")
                        .HasColumnType("int");

                    b.Property<int>("TravelPartyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TravelPartyID");

                    b.ToTable("TravelPerDiem");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelRateGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("CoachTravelRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MealPerDiemRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecruitTravelRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("TravelRateGroup");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrimarySchoolAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnlyUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SchoolAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("SchoolUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SystemAdmin")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.Year", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("YearEntry")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Year");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.BudgetSector", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDesignation", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.DescriptorDescription", "DescriptorDescription")
                        .WithMany("DescriptorDesignations")
                        .HasForeignKey("DescriptorDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helm_Budget_System.Models.TransactionDescriptor", "TransactionDescriptor")
                        .WithMany("DescriptorDesignations")
                        .HasForeignKey("TransactionDescriptorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DescriptorDescription");

                    b.Navigation("TransactionDescriptor");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.ExpenseCategory", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.PayrollCategory", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.Revenue", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.BudgetSector", "BudgetSector")
                        .WithMany()
                        .HasForeignKey("BudgetSectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helm_Budget_System.Models.DescriptorDescription", "DescriptorDescription")
                        .WithMany()
                        .HasForeignKey("DescriptorDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helm_Budget_System.Models.RevenueCategory", "RevenueCategory")
                        .WithMany()
                        .HasForeignKey("RevenueCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helm_Budget_System.Models.Year", "Year")
                        .WithMany()
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetSector");

                    b.Navigation("DescriptorDescription");

                    b.Navigation("RevenueCategory");

                    b.Navigation("School");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.RevenueCategory", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TransactionDescriptor", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelAirfare", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.TravelParty", null)
                        .WithMany("TravelAirfares")
                        .HasForeignKey("TravelPartyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelAuto", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.TravelParty", null)
                        .WithMany("TravelAutos")
                        .HasForeignKey("TravelPartyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelLodging", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.TravelParty", null)
                        .WithMany("TravelLodgings")
                        .HasForeignKey("TravelPartyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelMiscellaneousExpense", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.TravelEntry", null)
                        .WithMany("TravelMiscellaneousExpenses")
                        .HasForeignKey("TravelEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelParty", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.TravelEntry", null)
                        .WithMany("TravelParties")
                        .HasForeignKey("TravelEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelPerDiem", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.TravelParty", null)
                        .WithMany("TravelPerDiems")
                        .HasForeignKey("TravelPartyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelRateGroup", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDescription", b =>
                {
                    b.Navigation("DescriptorDesignations");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TransactionDescriptor", b =>
                {
                    b.Navigation("DescriptorDesignations");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelEntry", b =>
                {
                    b.Navigation("TravelMiscellaneousExpenses");

                    b.Navigation("TravelParties");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelParty", b =>
                {
                    b.Navigation("TravelAirfares");

                    b.Navigation("TravelAutos");

                    b.Navigation("TravelLodgings");

                    b.Navigation("TravelPerDiems");
                });
#pragma warning restore 612, 618
        }
    }
}
