// <auto-generated />
using System;
using Helm_Budget_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helm_Budget_System.Migrations.Helm_Budget_Db
{
    [DbContext(typeof(Helm_Budget_DbContext))]
    [Migration("20220504214859_Setting2")]
    partial class Setting2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Helm_Budget_System.Models.BudgetSector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BudgetSectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("BudgetSector");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDescription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DescriptorDescriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DescriptorDescription");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDesignation", b =>
                {
                    b.Property<int>("DescriptorDesignationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescriptorDesignationID"), 1L, 1);

                    b.Property<int>("DescriptorDescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("TransactionDescriptorID")
                        .HasColumnType("int");

                    b.HasKey("DescriptorDesignationID");

                    b.HasIndex("DescriptorDescriptionID");

                    b.HasIndex("TransactionDescriptorID");

                    b.ToTable("DescriptorDesignation");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ExpenseCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("ExpenseCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.PayrollCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal?>("AnnualBenefitRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("FringeBenefitRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PayrollCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("PayrollCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.RevenueCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("RevenueCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("RevenueCategory");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TransactionDescriptor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionDescriptorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("TransactionDescriptor");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelRateGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("CoachTravelRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MealPerDiemRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecruitTravelRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("TravelRateGroup");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrimarySchoolAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadOnlyUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SchoolAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("SchoolUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SystemAdmin")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.Year", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("YearEntry")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Year");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.BudgetSector", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDesignation", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.DescriptorDescription", "DescriptorDescription")
                        .WithMany("DescriptorDesignations")
                        .HasForeignKey("DescriptorDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helm_Budget_System.Models.TransactionDescriptor", "TransactionDescriptor")
                        .WithMany("DescriptorDesignations")
                        .HasForeignKey("TransactionDescriptorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DescriptorDescription");

                    b.Navigation("TransactionDescriptor");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.ExpenseCategory", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.PayrollCategory", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.RevenueCategory", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TransactionDescriptor", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TravelRateGroup", b =>
                {
                    b.HasOne("Helm_Budget_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.DescriptorDescription", b =>
                {
                    b.Navigation("DescriptorDesignations");
                });

            modelBuilder.Entity("Helm_Budget_System.Models.TransactionDescriptor", b =>
                {
                    b.Navigation("DescriptorDesignations");
                });
#pragma warning restore 612, 618
        }
    }
}
